#!/usr/bin/with-contenv bash

# copy

[[ ! -f /config/rslsync.conf ]] && \
	/usr/bin/rslsync --dump-sample-config > /config/rslsync.conf
	sed -i '7a "check_for_updates" : false,' /config/rslsync.conf
	sed -i 's/"listening_port" : 0,/"listening_port" : 50000,/g' /config/rslsync.conf
	sed -i 's@// "pid_file"@"pid_file"@g' /config/rslsync.conf

# permissions
chown abc:abc -R \
	/config